# Generated by Django 6.0.3 on 2026-03-28 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_alter_claimrequest_options_alter_founditem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Books', 'Books & Study Material'), ('Electronics', 'Electronics & Gadgets'), ('Furniture', 'Hostel Furniture'), ('Clothing', 'Clothing & Accessories'), ('Other', 'Miscellaneous')], max_length=30)),
                ('condition', models.CharField(choices=[('New', 'Brand New'), ('Like New', 'Excellent / Like New'), ('Used', 'Good / Used'), ('Rough', 'Fair / Functional')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/')),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
