# Generated by Django 6.0.6 on 2026-06-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_alter_form_organizer_club_form_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner'), ('Additional Meal', 'Additional Meal')], max_length=20),
        ),
    ]
