# Generated by Django 6.0.3 on 2026-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0002_emailotp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allocation',
            name='unique_active_allocation_per_user',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'confirmed'])), fields=('user',), name='unique_active_allocation_per_user'),
        ),
    ]
