# Generated by Django 6.0.6 on 2026-06-14 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0003_remove_allocation_unique_active_allocation_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date when the student vacates the room', null=True),
        ),
        migrations.AddField(
            model_name='complaintmaintenance',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Linked database room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostels.room'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('Boys', 'Boys Hostel'), ('Girls', 'Girls Hostel'), ('Co-ed', 'Co-ed Hostel')], default='Boys', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('vacated', 'Vacated')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaintmaintenance',
            name='room_number',
            field=models.CharField(help_text='Legacy or manual room number entry', max_length=10),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('departure_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpasses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
