# Generated by Django 6.0.6 on 2026-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0004_allocation_end_date_complaintmaintenance_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
