# Generated by Django 6.0.6 on 2026-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0005_liveannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmaintenance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
